first_num = int(input("Give me the first number: "))
sec_num = int(input("Give me the second number: "))
print("Thank you!")
print(first_num, "+", sec_num, "=", first_num + sec_num)
print(first_num, "-", sec_num, "=", first_num - sec_num)
print(first_num, "/", sec_num, "=", first_num // sec_num)
print(first_num, "*", sec_num, "=", first_num * sec_num)
